import type { QuizData } from "./types"

export const quizData: QuizData = {
  id: "astrology-quiz",
  title: "nordastro",
  description: "Discover your personalized astrology reading",
  questions: [
    {
      id: "q1",
      text: "What are your main goals?",
      subtitle: "Choose all that apply",
      multiSelect: true,
      minSelections: 1,
      options: [
        {
          id: "q1-a",
          text: "Understand myself better",
          icon: "🚀",
          resultMapping: {
            "self-discovery": 3,
            "career-growth": 1,
            relationship: 1,
            spiritual: 2,
          },
        },
        {
          id: "q1-b",
          text: "Discover my life path & purpose",
          icon: "🧘",
          resultMapping: {
            "self-discovery": 3,
            "career-growth": 2,
            relationship: 0,
            spiritual: 3,
          },
        },
        {
          id: "q1-c",
          text: "Find happiness",
          icon: "😊",
          resultMapping: {
            "self-discovery": 2,
            "career-growth": 1,
            relationship: 2,
            spiritual: 2,
          },
        },
        {
          id: "q1-d",
          text: "Improve my relationships",
          icon: "💖",
          resultMapping: {
            "self-discovery": 1,
            "career-growth": 0,
            relationship: 5,
            spiritual: 1,
          },
        },
        {
          id: "q1-e",
          text: "Get career guidance",
          icon: "💰",
          resultMapping: {
            "self-discovery": 1,
            "career-growth": 5,
            relationship: 0,
            spiritual: 0,
          },
        },
        {
          id: "q1-f",
          text: "Grow spiritually",
          icon: "🌸",
          resultMapping: {
            "self-discovery": 2,
            "career-growth": 0,
            relationship: 1,
            spiritual: 5,
          },
        },
        {
          id: "q1-g",
          text: "Get future predictions",
          icon: "🔮",
          resultMapping: {
            "self-discovery": 1,
            "career-growth": 2,
            relationship: 1,
            spiritual: 3,
          },
        },
        {
          id: "q1-h",
          text: "Other",
          icon: "🤔",
          resultMapping: {
            "self-discovery": 1,
            "career-growth": 1,
            relationship: 1,
            spiritual: 1,
          },
        },
      ],
    },
    {
      id: "q2",
      text: "When were you born?",
      subtitle: "Select your date of birth",
      multiSelect: false,
      requireDateOfBirth: true,
      options: [
        {
          id: "q2-a",
          text: "January - March",
          icon: "♈",
          isHidden: true,
          resultMapping: {
            aries: 3,
            taurus: 0,
            gemini: 0,
            cancer: 0,
            leo: 0,
            virgo: 0,
            libra: 0,
            scorpio: 0,
            sagittarius: 0,
            capricorn: 2,
            aquarius: 2,
            pisces: 2,
          },
        },
        {
          id: "q2-b",
          text: "April - June",
          icon: "♊",
          isHidden: true,
          resultMapping: {
            aries: 0,
            taurus: 3,
            gemini: 3,
            cancer: 2,
            leo: 0,
            virgo: 0,
            libra: 0,
            scorpio: 0,
            sagittarius: 0,
            capricorn: 0,
            aquarius: 0,
            pisces: 0,
          },
        },
        {
          id: "q2-c",
          text: "July - September",
          icon: "♌",
          isHidden: true,
          resultMapping: {
            aries: 0,
            taurus: 0,
            gemini: 0,
            cancer: 1,
            leo: 3,
            virgo: 3,
            libra: 1,
            scorpio: 0,
            sagittarius: 0,
            capricorn: 0,
            aquarius: 0,
            pisces: 0,
          },
        },
        {
          id: "q2-d",
          text: "October - December",
          icon: "♐",
          isHidden: true,
          resultMapping: {
            aries: 0,
            taurus: 0,
            gemini: 0,
            cancer: 0,
            leo: 0,
            virgo: 0,
            libra: 2,
            scorpio: 3,
            sagittarius: 3,
            capricorn: 1,
            aquarius: 0,
            pisces: 0,
          },
        },
      ],
    },
    {
      id: "q3",
      text: "What time of day were you born?",
      subtitle: "Select the closest option",
      multiSelect: false,
      options: [
        {
          id: "q3-a",
          text: "Morning (6am - 12pm)",
          icon: "🌅",
          resultMapping: {
            "rising-sun": 3,
            "high-noon": 1,
            "setting-sun": 0,
            "night-sky": 0,
          },
        },
        {
          id: "q3-b",
          text: "Afternoon (12pm - 6pm)",
          icon: "☀️",
          resultMapping: {
            "rising-sun": 0,
            "high-noon": 3,
            "setting-sun": 1,
            "night-sky": 0,
          },
        },
        {
          id: "q3-c",
          text: "Evening (6pm - 12am)",
          icon: "🌇",
          resultMapping: {
            "rising-sun": 0,
            "high-noon": 0,
            "setting-sun": 3,
            "night-sky": 1,
          },
        },
        {
          id: "q3-d",
          text: "Night (12am - 6am)",
          icon: "🌃",
          resultMapping: {
            "rising-sun": 0,
            "high-noon": 0,
            "setting-sun": 0,
            "night-sky": 3,
          },
        },
      ],
    },
    {
      id: "q4",
      text: "Where were you born?",
      subtitle: "Select the region",
      multiSelect: false,
      options: [
        {
          id: "q4-a",
          text: "North America",
          icon: "🌎",
          resultMapping: {
            western: 3,
            eastern: 0,
            southern: 0,
            northern: 1,
          },
        },
        {
          id: "q4-b",
          text: "Europe",
          icon: "🌍",
          resultMapping: {
            western: 1,
            eastern: 1,
            southern: 0,
            northern: 2,
          },
        },
        {
          id: "q4-c",
          text: "Asia",
          icon: "🌏",
          resultMapping: {
            western: 0,
            eastern: 3,
            southern: 1,
            northern: 0,
          },
        },
        {
          id: "q4-d",
          text: "Other",
          icon: "🌐",
          resultMapping: {
            western: 1,
            eastern: 1,
            southern: 1,
            northern: 1,
          },
        },
      ],
    },
  ],
  results: [
    {
      id: "aries",
      title: "Aries Rising",
      subtitle: "The Pioneer",
      description:
        "Your birth chart reveals a strong Aries influence, making you naturally courageous and pioneering. You approach life with enthusiasm and aren't afraid to take the lead. Your personalized astrology reading shows that you have a natural ability to initiate projects and inspire others.",
      image: "♈",
      recommendations: [
        "Channel your natural leadership abilities into projects you're passionate about",
        "Practice patience in situations that require a slower approach",
        "Balance your independence with meaningful connections",
        "Use your courage to overcome obstacles in your career path",
      ],
    },
    {
      id: "taurus",
      title: "Taurus Rising",
      subtitle: "The Steady Builder",
      description:
        "Your birth chart shows a prominent Taurus influence, giving you natural persistence and reliability. You value stability and have a practical approach to achieving your goals. Your personalized astrology reading indicates that you have a strong connection to the material world and appreciate beauty and comfort.",
      image: "♉",
      recommendations: [
        "Use your natural persistence to build long-term security",
        "Embrace change occasionally to avoid becoming too rigid",
        "Nurture your appreciation for beauty and the arts",
        "Balance material comfort with spiritual growth",
      ],
    },
    {
      id: "gemini",
      title: "Gemini Rising",
      subtitle: "The Communicator",
      description:
        "Your birth chart reveals a significant Gemini influence, giving you versatility and excellent communication skills. You're naturally curious and enjoy learning about a wide range of subjects. Your personalized astrology reading shows that you thrive in environments that offer variety and intellectual stimulation.",
      image: "♊",
      recommendations: [
        "Channel your communication skills into writing or teaching",
        "Practice focusing on one project at a time to avoid scattered energy",
        "Use your adaptability to navigate changing circumstances",
        "Balance intellectual pursuits with emotional connections",
      ],
    },
    {
      id: "cancer",
      title: "Cancer Rising",
      subtitle: "The Nurturer",
      description:
        "Your birth chart shows a strong Cancer influence, giving you natural empathy and intuition. You're deeply connected to your emotions and have a nurturing approach to relationships. Your personalized astrology reading indicates that you value security and have a strong connection to your home and family.",
      image: "♋",
      recommendations: [
        "Use your emotional intelligence to build meaningful relationships",
        "Create a nurturing home environment that supports your well-being",
        "Balance caring for others with self-care",
        "Trust your intuition when making important decisions",
      ],
    },
    {
      id: "leo",
      title: "Leo Rising",
      subtitle: "The Creative Leader",
      description:
        "Your birth chart reveals a prominent Leo influence, giving you natural charisma and creative energy. You have a warm, generous approach to life and aren't afraid to express yourself. Your personalized astrology reading shows that you have leadership potential and thrive when you receive recognition for your contributions.",
      image: "♌",
      recommendations: [
        "Channel your creative energy into artistic or leadership pursuits",
        "Practice humility to balance your natural confidence",
        "Use your warmth and generosity to inspire others",
        "Balance seeking recognition with giving praise to others",
      ],
    },
    {
      id: "virgo",
      title: "Virgo Rising",
      subtitle: "The Analytical Perfectionist",
      description:
        "Your birth chart shows a significant Virgo influence, giving you analytical skills and attention to detail. You have a practical approach to problem-solving and strive for improvement in all areas of life. Your personalized astrology reading indicates that you have a natural ability to organize and create efficient systems.",
      image: "♍",
      recommendations: [
        "Use your analytical skills to solve complex problems",
        "Practice self-acceptance to balance your perfectionist tendencies",
        "Channel your desire for improvement into meaningful work",
        "Balance critical thinking with compassion for yourself and others",
      ],
    },
  ],
}
